### ISSUE TITLE
matplotlib.rb V/s Python matplotlib

### ISSUE THREAD

**Issue by Shekharrajak** [mrkn/matplotlib.rb#2]
Does `matplotlib.rb` have all the features of python library `matplotlib` ?

**Comment by Shekharrajak** [comment]
I am looking for a plotting library for the [Daru](https://github.com/SciRuby/daru). Ping @mrkn ?

**Comment by mrkn** [comment]
Yes, it is just a wrapper of Python's matplotlib.

**Comment by Shekharrajak** [comment]
I didn't understand why these error are coming : 

```
irb(main):007:0* ax = plt.subplot(111, projection='polar')
PyCall::PyError: pytype(ValueError): ValueError(u"Illegal argument(s) to subplot: (111, 'polar')",)
```
```
c = ax.scatter(theta, r, c=colors, s=area, cmap="hsv", alpha=0.75)
PyCall::PyError: pytype(ValueError): ValueError(u'Unrecognized marker style hsv',)
```
```
c = ax.scatter(theta, r, c=colors, s=area, alpha=0.75)
PyCall::PyError: pytype(ValueError): ValueError(u'Unrecognized marker style 0.75',)
```
Can you help me to find out the error or syntax ? Thanks !

**Comment by mrkn** [comment]
In Ruby, the keyword argument syntax is `key: value`, that is different from Python's `key=value`.

**Comment by Shekharrajak** [comment]
Ah! my mistake. Thanks !
